spring:
  application:
    name: estudojpa
  output:
    ansi:
      enabled : ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5431/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
logging:
  file:
    name: app.log
  level:
    root: warn
    com:
      library:
        library: trace
    org:
      springframework:
        web: debug
        security : trace

server:
  port: 8081

