spring:
  application:
    name: libraryapi
#  profiles:
#    active: production
#  S´RING_PROFILES_ACTIVE=production
  output:
    ansi:
      enabled : ALWAYS
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5431/library}
    username: ${DATASOURCE_USERNAME:postgres}
    password:  ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
logging:
  file:
    name: app.log
  level:
    root: warn
    com:
      library:
        library: trace
    org:
      springframework:
        web: debug
        security : trace

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8081

#production
---
spring:
  config:
    activate:
      on-profile: production, homologacao
  jpa:
    show-sql: false

